# Generated by Django 4.0.5 on 2022-11-01 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auction_listing_listing_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_comments', to='auctions.auction_comments'),
        ),
    ]
