# Generated by Django 4.0.5 on 2022-11-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auction_listing_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='listing_pic',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
