# Generated by Django 4.0.5 on 2022-11-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auction_listing_watchlist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='starting_bid',
            new_name='price',
        ),
    ]
