# Generated by Django 4.0.5 on 2022-11-09 09:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_starting_bid_auction_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='starting_bid',
            field=models.ManyToManyField(blank=True, null=True, related_name='starting_bid', to=settings.AUTH_USER_MODEL),
        ),
    ]
