# Generated by Django 4.0.5 on 2022-11-09 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auction_listing_starting_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='starting_bid',
        ),
        migrations.CreateModel(
            name='starting_bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usersbid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_bid', to='auctions.starting_bid'),
        ),
    ]
