# Generated by Django 4.0.5 on 2022-11-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_auction_listing_starting_bid_starting_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starting_bid',
            name='bid',
            field=models.IntegerField(default=0),
        ),
    ]
